sylius_grid:
  grids:
    mango_sylius_admin_contact_message:
      driver:
        name: doctrine/orm
        options:
          class: MangoSylius\SyliusContactFormPlugin\Entity\ContactFormMessage
      limits: [10, 25, 50, 100]
      fields:
        createdAt:
          type: datetime
          label: mango_contact_form_plugin.label.date
          sortable: ~
          options:
            format: d-m-Y H:i:s
        customerName:
          type: string
          sortable: ~
          label: mango_contact_form_plugin.label.name
        email:
          type: string
          sortable: ~
          label: mango_contact_form_plugin.label.email
        phone:
          type: string
          label: mango_contact_form_plugin.label.phone
        message:
          type: twig
          label: mango_contact_form_plugin.label.message
          options:
            template: '@MangoSyliusContactFormPlugin/Admin/Grid/message.html.twig'
      sorting:
        createdAt: desc
      filters:
        search:
          type: string
          options:
            fields: [customerName, email, message]
      actions:
        item:
          show_message:
            type: show
            label: mango_contact_form_plugin.ui.show_message
            options:
              link:
                route: mango_sylius_admin_contact_show
                parameters:
                  id: resource.id

    mango_sylius_account_contact_message:
      driver:
        name: doctrine/orm
        options:
          class: MangoSylius\SyliusContactFormPlugin\Entity\ContactFormMessage
          repository:
            method: findAllByCustomerId
            arguments: ['expr:service("sylius.context.customer").getCustomer().getId()']
      limits: [10, 25, 50, 100]
      fields:
        createdAt:
          type: datetime
          label: mango_contact_form_plugin.label.date
          sortable: ~
          options:
            format: d-m-Y H:i:s
        message:
          type: twig
          label: mango_contact_form_plugin.label.message
          options:
            template: '@MangoSyliusContactFormPlugin/Admin/Grid/message.html.twig'
      sorting:
        createdAt: desc
      actions:
        item:
          show_message:
            type: show
            label: mango_contact_form_plugin.ui.show_message
            options:
              link:
                route: mango_sylius_contact_form_shop_account_message_show
                parameters:
                  id: resource.id
